### PR TITLE
Deploy with Ansistrano

### PR DESCRIPTION
**Pull request by jgavris**
https://app.asana.com/0/346597215964070/351264698868632

- Deploy new code to `gambler` by doing `rake deploy` (annoyingly ansible's rsync module still appears to be broke and requires a password).
- Installs the service as a system service that starts on launch. 
- Log file available at `~/srv/bazel-rest-cache/bazel-rest-cache.log`.

### CODE REVIEW

**Comment by sschaetz** [comment]
Oh boy. I missed the bazel train and now I don't know what's going on any longer. Informal brown bag talk? :-)

**Comment by jgavris** [comment]
Sure! This repo is a very lightweight caching server we can plug into bazel using the lightly documented `--remote_rest_cache` remote spawn strategy, which I've implemented here

https://github.com/ButterflyNetwork/software/pull/2476/files#diff-0272d158c9ceffb78f9e8c6b828108e6R1

This is a simple Swift / Kitura app backed by redis (40GB max, with LRU eviction) that implements the bazel REST cache API (HEAD / GET / PUT /cache/<key>). 

The idea is that when you (or a build agent) completes an 'action', the results of that action are put in the cache, using a key derived from the inputs. If another process has the same set of inputs and produces the same action key, bazel can just pull the action outputs from the cache. You can build `ImagingSandbox`, delete the output file locally, build it again, and it should pull it down super fast-like from gambler.

**Comment by sschaetz** [comment]
That's awesome. 'Action' is very general. Is it typically a build (input files + flags and you get a binary back maybe?) or can it also be a test result (input binary and flags, get result)?

**Comment by jgavris** [comment]
They're the same AFAIK. You should have to declare any inputs for any rule (making network requests / USB comms is probably going to be a challenge for test caching).

**Comment by jgavris** [comment]
Here's a design document for where the remote execution API is going...building on top of remote action caching.

https://docs.google.com/document/d/1AaGk7fOPByEvpAbqeXIyE8HX_A3_axxNnvroblTZ_6s/edit#heading=h.ole76l21af90

**Pull request merged**
